/**
 * @author Maria Fernanda Serna
 */

export const GETHOTELLIST_REQUEST = 'GETHOTELLIST_REQUEST';
export const GETHOTELLIST_REQUEST_FAIL = 'GETHOTELLIST_REQUEST_FAIL';
export const GETHOTELLIST_REQUEST_SUCCESS = 'GETHOTELLIST_REQUEST_SUCCESS';
