/**
 * @author Maria Fernanda Serna
 */

export const GETHOTELBYID_REQUEST = 'GETHOTELBYID_REQUEST_REQUEST';
export const GETHOTELBYID_REQUEST_FAIL = 'GETHOTELBYID_REQUEST_FAIL';
export const GETHOTELBYID_REQUEST_SUCCESS = 'GETHOTELBYID_REQUEST_SUCCESS';
